name: Publish

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: corretto
    - name: Gradle Setup
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false
    - name: Get published version
      id: version_info
      run: |
        ./gradlew
        VERSION_CODE="v""$(gradle printVersion -q)"
        echo $VERSION_CODE
        echo -n "::set-output name=VERSION_CODE::$VERSION_CODE"
    - name: Check version matches tag
      if: ${{ steps.version_info.outputs.VERSION_CODE != github.ref_name }}
      run: |
        echo "Artifact version ${{ steps.version_info.outputs.VERSION_CODE }} does not match git tag ${{ github.ref_name }}
        exit 1
    - name: Publish with Gradle
      run: gradle clean test publish
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_USERNAME: ${{ secrets.USERNAME }}
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        generate_release_notes: true
